name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.4']

    services:
      oracle:
        image: gvenzl/oracle-free:23-slim
        env:
          ORACLE_PASSWORD: oracle
          APP_USER: hr
          APP_USER_PASSWORD: hr
        ports:
          - 1521:1521
        options: >-
          --health-cmd="healthcheck.sh"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=10
          --health-start-period=120s
          --shm-size=1g

      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: YourStrong@Passw0rd
        ports:
          - 1433:1433
        options: >-
          --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q 'SELECT 1'"
          --health-interval=10s
          --health-timeout=3s
          --health-retries=10
          --health-start-period=10s

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install Oracle Instant Client
      run: |
        sudo apt-get update
        sudo apt-get install -y libaio1t64 alien

        # Download Oracle Instant Client
        wget https://download.oracle.com/otn_software/linux/instantclient/2340000/oracle-instantclient-basic-23.4.0.24.05-1.el9.x86_64.rpm
        wget https://download.oracle.com/otn_software/linux/instantclient/2340000/oracle-instantclient-devel-23.4.0.24.05-1.el9.x86_64.rpm

        # Convert RPM to DEB and install
        sudo alien -i oracle-instantclient-basic-23.4.0.24.05-1.el9.x86_64.rpm
        sudo alien -i oracle-instantclient-devel-23.4.0.24.05-1.el9.x86_64.rpm

        # Set up environment
        echo "/usr/lib/oracle/23/client64/lib" | sudo tee /etc/ld.so.conf.d/oracle-instantclient.conf
        sudo ldconfig

    - name: Install FreeTDS for SQL Server
      run: |
        sudo apt-get install -y freetds-dev

    - name: Install gems
      run: bundle install
      env:
        LD_LIBRARY_PATH: /usr/lib/oracle/23/client64/lib
        ORACLE_HOME: /usr/lib/oracle/23/client64

    - name: Run Oracle specs
      run: bundle exec rspec
      env:
        LD_LIBRARY_PATH: /usr/lib/oracle/23/client64/lib
        ORACLE_HOME: /usr/lib/oracle/23/client64
        DATABASE_TYPE: oracle
        ORACLE_HOST: localhost
        ORACLE_PORT: 1521
        ORACLE_SID: FREE
        ORACLE_USER: hr
        ORACLE_PASSWORD: hr

    - name: Run SQL Server specs
      run: bundle exec rspec
      env:
        DATABASE_TYPE: sqlserver
        SQLSERVER_HOST: localhost
        SQLSERVER_PORT: 1433
        SQLSERVER_USER: sa
        SQLSERVER_PASSWORD: YourStrong@Passw0rd
