name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3', '3.4']

    services:
      oracle:
        image: gvenzl/oracle-xe:21-slim
        env:
          ORACLE_PASSWORD: oracle
          APP_USER: hr
          APP_USER_PASSWORD: hr
        ports:
          - 1521:1521
        options: >-
          --health-cmd="healthcheck.sh"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=10
          --health-start-period=120s
          --shm-size=1g

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install Oracle Instant Client
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip libaio1
        wget https://download.oracle.com/otn_software/linux/instantclient/2340000/instantclient-basic-linux.x64-23.4.0.24.05.zip
        wget https://download.oracle.com/otn_software/linux/instantclient/2340000/instantclient-sdk-linux.x64-23.4.0.24.05.zip
        sudo mkdir -p /opt/oracle
        sudo unzip instantclient-basic-linux.x64-23.4.0.24.05.zip -d /opt/oracle/
        sudo unzip instantclient-sdk-linux.x64-23.4.0.24.05.zip -d /opt/oracle/
        echo "/opt/oracle/instantclient_23_4" | sudo tee /etc/ld.so.conf.d/oracle-instantclient.conf
        sudo ldconfig

    - name: Install gems
      run: bundle install
      env:
        LD_LIBRARY_PATH: /opt/oracle/instantclient_23_4
        ORACLE_HOME: /opt/oracle/instantclient_23_4

    - name: Run specs
      run: bundle exec rspec
      env:
        LD_LIBRARY_PATH: /opt/oracle/instantclient_23_4
        ORACLE_HOME: /opt/oracle/instantclient_23_4
        ORACLE_HOST: localhost
        ORACLE_PORT: 1521
        ORACLE_SID: freepdb1
        ORACLE_USER: hr
        ORACLE_PASSWORD: hr